# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lakshitha Vimuth
title: Bio Medical Researcher / Machine Learning Engineer
email: lakshithavimuth8@gmail.com
website: lvimuth.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lvimuth
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: lvimuth
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# Additional icon links
additional_links:
- title: Medium link
  icon: fab fa-medium
  url: https://medium.com/@lvimuth
- title: Hackerrank link
  icon: fab fa-hackerrank
  url: https://www.hackerrank.com/profile/lvimuthfb

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Vimuth and I'm a Machine Learning Engineer. As an Electrical and Telecommunication Engineering graduate, I am deeply passionate about AI and ML, with a strong foundation in Python, PLC, web development, and Java. My focus on image processing and AI is backed by practical projects and research. I am keen to contribute my diverse skills to roles that harness my engineering background and burgeoning expertise in Data Science and AI, aiming to drive innovation and tackle complex challenges.

  I am most skilled in: <mark>MLOps</mark> , <mark>Artificial Intelligence in Healthcare</mark> and <mark>Python</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sparklo General Machinery LLC - UAE 
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: IoT Engineer
        caption: November 2023 - Present
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          AI/ML Integration in IoT: Pioneered the incorporation of AI and ML into IoT devices, elevating automation and predictive capabilities, and contributing to a smarter device ecosystem.
          
          Data-Driven IoT Analytics: Applied ML models for real-time IoT sensor data analysis, enhancing decision-making and predictive maintenance.
          
          Collaborative Design: Led interdisciplinary teams in harmonizing AI and IoT functionalities, ensuring optimal device performance and user satisfaction.
          
          Custom IoT Solutions: Directed on-site evaluations and crafted AI-powered IoT solutions tailored to client specifications, boosting operational efficiency and achieving a 120% surge in market demand.
          
          Innovation and Scalability: Developed scalable AI-integrated IoT frameworks, accommodating increased data and complexity, and spearheaded continuous tech advancements.
          
          Security and Efficiency: Implemented AI-enhanced security in IoT networks, significantly improving data integrity and system efficiency.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  #- title: A Little More About Me
   # layout: text
    #content: | # this will include new lines to allow paragraphs
     # Alongside my interests in networks and software engineering some of my other interests and hobbies are:
     # - Rock climbing
     # - Gaming
     # - Knitting
     # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
